name: Upload .tfstate to AWS S3

on: 
  workflow_call:
    inputs:
      resource:
        required: true
        type: string
  
jobs:
  download-S3:
    runs-on: ubuntu-latest
    outputs:
      arquivo-gerado: ${{ steps.gerar.outputs.nome_arquivo }}
    steps:

    - name: Check Out
      uses: actions/checkout@v4

    - name: AWS Login
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2          
      
    - name: .tfstate Download
      run: aws s3 cp s3://terraform-tfstate-bucket-davi/${{ inputs.resource }}/terraform.tfstate ./


    - name: Gerar Arquivo
      id: gerar
      run: echo "::set-output name=nome_arquivo::terraform.tfstate"

    - name: Upload Artefato
      uses: actions/upload-artifact@v4
      with:
        name: arquivo-gerado-reutilizavel
        path: terraform.tfstate
