name: Upload .tfstate to AWS S3

on: 
  workflow_call:
  
  workflow_dispatch:
    inputs:
      environment:
        description: 'Tipo de ação'
        required: true
        default: 'apply'
        type: choice
        options:
        - apply
        - destroy

jobs:
  uploadS3:
    runs-on: ubuntu-latest
    steps:

    - name: Check Out
      uses: actions/checkout@v4

    - name: teste
      run: | 
        echo 'oi, vim do repo do upload para o s3'
      
